### ISSUE TITLE
Cover Image

### ISSUE THREAD

**Issue by ghost** [nitinthewiz/ghost-phantom#10]
@haydenbleasel Hey!

In the readme, it never mentions how to upload the cover image.

How does it work?

Thanks.

**Comment by haydenbleasel** [comment]
Hey @nahtnam, are you referring to the generic cover photo (shown on the hompeage) or the post photo (shown on the top of each post)? Also, is this for Phantom, Vignette or Cactus theme?

**Comment by ghost** [comment]
Both?

On Saturday, October 18, 2014, Hayden Bleasel notifications@github.com
wrote:

> Hey @nahtnam https://github.com/nahtnam, are you referring to the
> generic cover photo (shown on the hompeage) or the post photo (shown on the
> top of each post)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/haydenbleasel/ghost-themes/issues/10#issuecomment-59636828
> .

## 

Thanks,
Manthan Mallikarjun (http://nahtnam.com)

**Comment by haydenbleasel** [comment]
Assuming you're on Ghost 0.5.2, the cover can be changed on the [settings page](https://assets.digitalocean.com/articles/ghost_use/gen_settings.png) and the post photo can be set on the new [post settings panel](http://blog.balintant.me/content/images/2014/09/-2014-09-26-at-4-08-22-pm.png).

**Comment by ghost** [comment]
Oh wow! A lot has changed about ghost in the past 6 months!

Thanks!

On Saturday, October 18, 2014, Hayden Bleasel notifications@github.com
wrote:

> Assuming you're on Ghost 0.5.2, the cover can be changed on the settings
> page https://assets.digitalocean.com/articles/ghost_use/gen_settings.png
> and the post photo can be set on the new post settings panel
> http://blog.balintant.me/content/images/2014/09/-2014-09-26-at-4-08-22-pm.png
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/haydenbleasel/ghost-themes/issues/10#issuecomment-59638118
> .

## 

Thanks,
Manthan Mallikarjun (http://nahtnam.com)

**Comment by haydenbleasel** [comment]
No worries!
