### ISSUE TITLE
Image On Author Page

### ISSUE THREAD

**Issue by ghost** [nitinthewiz/ghost-phantom#11]
Hey!

Just a suggestion: Show the authors image when viewing the authors page. https://domain.com/author/USERNAME/

**Comment by haydenbleasel** [comment]
Sounds like a good idea haha. What theme is this for? (Phantom, Cactus or Vignette)

**Comment by haydenbleasel** [comment]
Whoops, hit the comment + close button.

**Comment by ghost** [comment]
@haydenbleasel Phantom!

**Comment by haydenbleasel** [comment]
Okay no worries, I'll have a look into this! Btw, if it's not obvious, themes on `ghost-themes` are separated by branches.

**Comment by ghost** [comment]
Yeah, I just noticed! :P

Thanks!

Thanks,
Manthan Mallikarjun (http://nahtnam.com)

**Comment by haydenbleasel** [comment]
@nahtnam Snazzy new author header.

![screenshot 2014-10-30 21 07 00](https://cloud.githubusercontent.com/assets/4142719/4841651/c83b2ac4-601c-11e4-99d4-f1cbd382fee5.png)

**Comment by ghost** [comment]
Awesome. I'll update my site with the new theme!
