### ISSUE TITLE
Indenting partials causes unexpected results

### ISSUE THREAD

**Issue by ErisDS** [nitinthewiz/ghost-phantom#14]
A user of the phantom theme reported an issue on the [ghost forum](https://ghost.org/forum/using-ghost/16929-indentations-syntax-highlightling/) where code blocks were rendering with extra indentation.

I narrowed the issue down to being a problem with the `{{>content}}` partial used to output content. The code to include the partial is indented one level, which handlebars then respects and applies to all the content output by the partial. This is apparently a change to [how handlebars works](https://github.com/wycats/handlebars.js/issues/858) which may get a flag to disable.

In the meantime, I will look to downgrade the version of handlebars we use in Ghost, but also it may be worth updating your themes to remove the indentation from the `{{>content}}` partial.

**Comment by haydenbleasel** [comment]
@ErisDS Okay, thanks for the heads up champion :+1:
