### ISSUE TITLE
Tags cant not click

### ISSUE THREAD

**Issue by edwardstudy** [nitinthewiz/ghost-phantom#16]
Hi, Thank you because I have used your theme on [my blog](http://edwardesire.com),but I think it has a problem of "click tags".
When I go to homepage, the second tag and others can not click right way in left sidebar(class="sidebar text-right meta")(only one tag can be clicked), so I changed the css of article
lick that

```
article {
    -webkit-animation-delay:1.25s;
    animation-delay:1.25s;
    -webkit-animation-duration:1s;
    animation-duration:1s;
    padding:0px 0 40px;
    margin-top: 80px;
}
```

Is it a good way to fix it, or maybe you have a better way?

Thx.

**Comment by haydenbleasel** [comment]
The `article` tag is overlapping the absolute-positioned `.sidebar` element. I'll fix this up when I get a chance, sorry!

**Comment by edwardstudy** [comment]
I'm really looking forward to seeing your fix,^_^

**Comment by kyleroche** [comment]
I used this... I think it has less of an offensive whitespace than the 80px. But seems to work fine: 

article {
   -webkit-animation-delay:1.25s;
   animation-delay:1.25s;
   -webkit-animation-duration:1s;
   animation-duration:1s;
   padding:40px 0;
    position: relative;
    width: 700px;
    margin: 0px auto;
}
