### ISSUE TITLE
Phantom User Image

### ISSUE THREAD

**Issue by ghost** [nitinthewiz/ghost-phantom#19]
Hey @haydenbleasel!

Found a small UI bug. I have a huge avatar uploaded for myself. When I scroll to the bottom of any post, the avatar takes up all of the space. It would be great if you could add some CSS that limits the avatar image and also displays more information than the name.

**Comment by haydenbleasel** [comment]
Hey @nahtnam, thanks for reporting this! I'll look into it in a few days (after my exams). :+1:
