### ISSUE TITLE
Centering linked images

### ISSUE THREAD

**Issue by CMCDragonkai** [nitinthewiz/ghost-phantom#23]
This style of syntax:

```
[![Unified Log Diagram](http://engineering.linkedin.com/sites/default/files/datapipeline_simple.png)](http://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying)
```

Which creates a linked image, the image doesn't get centered however, because the surrounding p tag doesn't get the `article-image` class.

**Comment by haydenbleasel** [comment]
All fixed - I limited it to the `<p>` tag without thinking of this case.
