### ISSUE TITLE
Not sure how to include a cover photo

### ISSUE THREAD

**Issue by amoderate** [nitinthewiz/ghost-phantom#26]
The one I set in the blog settings does not show up and there is no instructions in the readme

**Comment by haydenbleasel** [comment]
Hey @amoderate, is this for the Phantom, Cactus or Vignette theme?

**Comment by dialnco** [comment]
if it's the Vignette I think its a problem with vignette.js . I got a couples of issues with chrome dev tools and the "blur" property :) kudos!

**Comment by djwaix** [comment]
No response yet? Did you get this figured out? I can't seem to get it working either — hosted Ghost(Pro) account.

I've actually tried Vingnette and Phantom...though, it seems they are currently the same?

**Comment by haydenbleasel** [comment]
@thadeej @dialnco These themes probably need updating to handle the newest version of Ghost but I haven't had time to check the newest Ghost spec.

**Comment by djwaix** [comment]
@haydenbleasel That's exactly the conclusion I came to after a little digging around. No worries. Ping us if you manage to get things updated. Beautiful themes, so I'd love to check them out.

**Comment by haydenbleasel** [comment]
@thadeej @amoderate @dialnco Hey guys, I'm retiring this Ghost theme (Vignette) so if anyone would like to take over it, let me know.

**Comment by haydenbleasel** [comment]
@thadeej @amoderate @dialnco Hey all. I'm retiring this Ghost theme (Vignette). If no-one here wants to take over, it will be deleted.
