### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by ipalindromi** [nitinthewiz/ghost-phantom#27]
I ran into this issue while installing the Phantom theme. I'm brand new to Ghost, so maybe I'm missing something obvious, but it seemed like the issue might also be related to http://dev.ghost.org/no-more-jquery/.

Manually adding jQuery to the footer works, but this isn't mentioned in the documentation. Would it make sense to include jQuery in the assets?

**Comment by haydenbleasel** [comment]
@ipalindromi Yep, looks like we need to update this theme (and the others) with jQuery. Is it possible to submit a PR?

**Comment by ipalindromi** [comment]
@haydenbleasel Sure, I'll look into it!
