### ISSUE TITLE
Online demo?

### ISSUE THREAD

**Issue by pascalandy** [nitinthewiz/ghost-phantom#29]
Hey Hayden,

Do you have a demo in prod ?

Cheers!
Pascal

**Comment by haydenbleasel** [comment]
Hey @pascalandy, I don't run a demo myself but there are plenty of people using Phantom (Google search "Phantom Hayden Bleasel") e.g.
- http://blog.zer0w1re.net/
- http://daniafaruqui.com/
- http://blog.sopamo.de/
- http://articles.novoresume.com/
- http://blog.bryanalexander.co/

Some have been edited but you get the idea :)

**Comment by amilajack** [comment]
Thanks!
