### ISSUE TITLE
Looking for new owner

### ISSUE THREAD

**Issue by haydenbleasel** [nitinthewiz/ghost-phantom#33]

**Comment by haydenbleasel** [comment]
Hey all,

It's come to my attention that a lot of people still love this theme as I've been getting many emails and comments about updating it. I'm looking for some contributors to take over the development of this theme and **make Phantom great again**. Lemme know if you're interested.

@UnbounDev @jonmholt @rrobe53 @nevi-me?

**Comment by haydenbleasel** [comment]
Ok, here goes then. Anyone who's forked:

@7x63so @90TechSAS @AgtLucas @andkon @AndrewKishino @antonsamper @baymax84 @bharley @bmartel @bradonmiyake @brentpayne @bryanbierce @burnsra @CABoomer @cerealco @chrisdalsgaard @chrisrickard @christopherdalsgaard @cihankoseoglu @cloudzombie @cristianrosu @d1rk @D3f4lt @deholic @dereklucas @devcken @developer-prosenjit @digideskio @egdirbt @eiriklv @enjikaka @forfuturellc @geoffmomin @Get404 @gregorjerak @haegyung @haelab @hamzamu @happyjiahan @HashDataInc @hexth @hikikomorime @hlive @hnode @holmlund @HunjaeJung @ifa6 @imranraja85 @innovate-technologies @intajay

**Comment by haydenbleasel** [comment]
@ipalindromi @isnerd @jacobwl @jeffm13 @johnnycopperstone @johnyc90 @jordanmwilliams @jpvantuyl @jslyonnais @jwelch92 @kancelott @karinaflor @kdelfour @kellymurray @kendall80 @kipdurney @kylecho @Leafpub @lohmander @luciferydy @macctown @manishchhabra @matthanley @mcbuzzaldrin @micahroberson @mohammedovich @morpheum @mruessler @mthlvt @mustafakisa @NahuelIanni @cooperaj @natbrown @naw2489 @netzhoerer @ngdelcastillo @ngurajeka @nickisnoble @nitinthewiz @no0dles @norsasono @nuisancelabs @pixeleet @praveenscience @qianyanseu @ReeSilva @richardlemon @rjatkinson2 @Roadchen @robertoriv

**Comment by haydenbleasel** [comment]
@rocknrollMarc @rpmalone @rsgoheen @ryngrn @samuelngs @sddamico @sethrutnertrr @ShaleApps @shinestrength @shit-works @sidigrid @SlimBN @splinterific @steven6143 @svandecappelle @techimpossible @techmanrc @teqnology @thaJeztah @theobarberbany @thiphariel @TuXinFeng @ucg8j @vboginskey @vedant @VincentBel @Virezox @vliminimvl @vokoshyv @wangzw @wcwung @weareredshift @WebsterFolksLabs @WenInCode @WildAndrewLee @willsoto @xuewang @YahirAlejandro @yangtingzhi @yizhigou @yxshawn @zackphilipps @zColdWater @zenparty

**Comment by nitinthewiz** [comment]
I just recently installed Ghost back after a while. I'd like to take a crack at this. How would we do this? I can take a look at the issues and start working my way through.

**Comment by haydenbleasel** [comment]
@nitinthewiz That's cool - there's 2 different themes in this repository: Phantom and Cactus. I can split one out into a new repository and give them to whoever wants to own + maintain them.

**Comment by lavabyrd** [comment]
To be honest my knowledge of ghost in general isn't great but i'm certainly willing it give it a look and if not, hand it over to someone who can :)

**Comment by nitinthewiz** [comment]
Great! I'll take Phantom and work through the code 😊

**Comment by haydenbleasel** [comment]
Great. @nitinthewiz @splinterific You'll both get emails soon.

**Comment by haydenbleasel** [comment]
@nitinthewiz @splinterific I just realised you'll need to delete your ghost-themes forks first.

**Comment by lavabyrd** [comment]
All gone @haydenbleasel (that was incredibly difficult to do on mobile)

**Comment by haydenbleasel** [comment]
@splinterific Nice one - check your email :)

**Comment by lavabyrd** [comment]
Got it! Thanks for all the hard work

**Comment by nitinthewiz** [comment]
@haydenbleasel deleted my fork too...

**Comment by haydenbleasel** [comment]
@nitinthewiz Great, you should get an email

**Comment by nitinthewiz** [comment]
@haydenbleasel thank you for all your amazing work on this theme! You mentioned that you've been getting emails about updating this theme. Can you forward me some? Or tell me your vision for the future of this theme and I'll work to create that.

**Comment by haydenbleasel** [comment]
I've actioned all the emails that came in, none left for now. The theme needs to be updated for the newest version of Ghost and there's #17 which definitely needs resolving. Other than that, just push it out and listen to the community, build what they need and you'll be set 👍

**Comment by thiphariel** [comment]
@haydenbleasel thanks for your work on this. And yeah, as  I remember, #17 would be really great for this theme !

Good luck to the new maintainers !

**Comment by praveenscience** [comment]
I am in... 😃
