### ISSUE TITLE
Increasing blog title size

### ISSUE THREAD

**Issue by philipobrien** [nitinthewiz/ghost-phantom#7]
Hi. I love your theme but I want to increase the size of the blog title at the top of the page from the default 18px to 24px. I have done this by just setting it as below. Is this the only element that will be affected?

```
.content {
  font-size:24px;
}
```

**Comment by haydenbleasel** [comment]
Hey @philipobrien, yeah the `.content` class is only applied to the title area. Pretty bad naming conventions but I'll get onto this in the next revision. Also I'd recommend creating a new stylesheet for overwrites and just plugging that into `default.hbs` so you're able to get the newest versions without losing changes!

**Comment by philipobrien** [comment]
Great, thanks!
